import { DownloadIcon,
  BellIcon,
  MoreDotIcon,
  FileIcon,
  GridIcon,
  AudioIcon,
  VideoIcon,
  BoltIcon,
  PlusIcon,
  BoxIcon,
  CloseIcon,
  CheckCircleIcon,
  AlertIcon,
  InfoIcon,
  ErrorIcon,
  ArrowUpIcon,
  FolderIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  GroupIcon,
  BoxIconLine,
  ShootingStarIcon,
  DollarLineIcon,
  TrashBinIcon,
  AngleUpIcon,
  AngleDownIcon,
  PencilIcon,
  CheckLineIcon,
  CloseLineIcon,
  ChevronDownIcon,
  PaperPlaneIcon,
  EnvelopeIcon,
  LockIcon,
  UserIcon,
  CalenderIcon,
  EyeIcon,
  EyeCloseIcon,
  TimeIcon,
  CopyIcon,
  ChevronLeftIcon,
  UserCircleIcon,
  ListIcon,
  TableIcon,
  PageIcon,
  TaskIcon,
  PieChartIcon,
  BoxCubeIcon,
  PlugInIcon,
  DocsIcon,
  MailIcon,
  HorizontaLDots,
  ChevronUpIcon,
  ChatIcon} from '@/icons'
import React from 'react'

const pages = () => {
  return (
    <div>
         <DownloadIcon/>
          <BellIcon/>
          <MoreDotIcon/>
          <FileIcon/>
          <GridIcon/>
          <AudioIcon/>
          <VideoIcon/>
          <BoltIcon/>
          <PlusIcon/>
          <BoxIcon/>
          <CloseIcon/>
          <CheckCircleIcon/>
          <AlertIcon/>
          <InfoIcon/>
          <ErrorIcon/>
          <ArrowUpIcon/>
          <FolderIcon/>
          <ArrowDownIcon/>
          <ArrowRightIcon/>
          <GroupIcon/>
          <BoxIconLine/>
          <ShootingStarIcon/>
          <DollarLineIcon/>
          <TrashBinIcon/>
          <AngleUpIcon/>
          <AngleDownIcon/>
          <PencilIcon/>
          <CheckLineIcon/>
          <CloseLineIcon/>
          <ChevronDownIcon/>
          <PaperPlaneIcon/>
          <EnvelopeIcon/>
          <LockIcon/>
          <UserIcon/>
          <CalenderIcon/>
          <EyeIcon/>
          <EyeCloseIcon/>
          <TimeIcon/>
          <CopyIcon/>
          <ChevronLeftIcon/>
          <UserCircleIcon/>
          <ListIcon/>
          <TableIcon/>
          <PageIcon/>
          <TaskIcon/>
          <PieChartIcon/>
          <BoxCubeIcon/>
          <PlugInIcon/>
          <DocsIcon/>
          <MailIcon/>
          <HorizontaLDots/>
          <ChevronUpIcon/>
          <ChatIcon/>
    </div>
  )
}

export default pages